packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@swc/core': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@scalar/client-side-rendering@0.4.1'
  - '@scalar/express-api-reference@0.10.19'
  - '@scalar/helpers@0.12.0'
  - '@scalar/schemas@0.10.0'
  - '@scalar/types@0.20.0'
  - '@tanstack/query-core@5.103.0'
  - '@tanstack/react-query@5.103.0'
  - '@types/node@22.20.3'
  - prettier@3.9.7
