"use client";

import Link from "next/link";
import { ArrowRight, Check, FileText, LayoutTemplate, Sparkles } from "lucide-react";
import { Button } from "~/components/ui/button";
import { authClient } from "~/lib/auth-client";

export default function Home() {
  const { data: session } = authClient.useSession();

  return (
    <main className="min-h-screen overflow-hidden bg-background text-foreground">
      <div className="absolute inset-x-0 top-0 h-[34rem] bg-[radial-gradient(circle_at_50%_-10%,color-mix(in_oklab,var(--primary)_16%,transparent),transparent_62%)]" />
      <nav className="relative mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <Link href="/" className="flex items-center gap-2 text-sm font-semibold tracking-[0.18em]"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Sparkles className="size-4" /></span>FTHEFORM</Link>
        <div className="flex items-center gap-3">{session?.user ? <Button asChild><Link href="/dashboard">Go to Dashboard <ArrowRight /></Link></Button> : <><Button asChild variant="ghost"><Link href="/login">Log in</Link></Button><Button asChild><Link href="/sign-up">Sign up <ArrowRight /></Link></Button></>}</div>
      </nav>
      <section className="relative mx-auto grid max-w-7xl items-center gap-16 px-6 pb-24 pt-16 lg:grid-cols-[1.05fr_0.95fr] lg:px-10 lg:pb-32 lg:pt-24">
        <div><p className="mb-6 flex items-center gap-2 text-sm font-medium uppercase tracking-[0.2em] text-muted-foreground"><span className="size-2 rounded-full bg-chart-2" />Form building, made human</p><h1 className="max-w-3xl text-5xl font-semibold leading-[1.02] tracking-tight sm:text-7xl">Ask better questions. <span className="text-muted-foreground">Get clearer answers.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">FTHEFORM helps you create focused forms that feel easy to complete and simple to act on. Less friction for people. More signal for you.</p><div className="mt-9 flex flex-wrap gap-3">{session?.user ? <Button asChild size="lg"><Link href="/dashboard">Go to Dashboard <ArrowRight /></Link></Button> : <><Button asChild size="lg"><Link href="/sign-up">Start building <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline"><Link href="/login">Log in</Link></Button></>}</div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Check className="size-4 text-chart-2" />Quick to create</span><span className="flex items-center gap-2"><Check className="size-4 text-chart-2" />Easy to share</span><span className="flex items-center gap-2"><Check className="size-4 text-chart-2" />Ready to use</span></div></div>
        <div className="relative min-h-[20rem] rounded-3xl border border-border bg-card p-5 shadow-2xl sm:p-8"><div className="absolute -right-5 -top-5 size-20 rounded-full border border-chart-2/30 bg-chart-2/10" /><div className="relative rounded-2xl border border-border bg-background p-5 sm:p-7"><div className="flex items-center justify-between border-b border-border pb-5"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">New form</p><h2 className="mt-2 text-xl font-semibold">Team pulse check-in</h2></div><FileText className="size-5 text-muted-foreground" /></div><div className="space-y-6 pt-6"><div><p className="text-sm font-medium">What should we keep doing?</p><div className="mt-3 h-10 rounded-md border border-border bg-muted/40" /></div><div><p className="text-sm font-medium">How are you feeling about the week?</p><div className="mt-3 grid grid-cols-3 gap-2"><div className="h-10 rounded-md border border-border bg-muted/40" /><div className="h-10 rounded-md border border-primary bg-primary/10" /><div className="h-10 rounded-md border border-border bg-muted/40" /></div></div><Button className="w-full">Publish form</Button></div></div></div>
      </section>
      <section className="relative border-t border-border bg-muted/30 px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-sm font-medium uppercase tracking-[0.2em] text-muted-foreground">A calmer way to collect input</p><div className="mt-10 grid gap-10 md:grid-cols-3"><div><LayoutTemplate className="size-5" /><h3 className="mt-5 text-lg font-semibold">Start with structure</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Shape a form around the decision you need to make, not a pile of fields.</p></div><div><Sparkles className="size-5" /><h3 className="mt-5 text-lg font-semibold">Keep it thoughtful</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">A focused experience invites better answers and respects people&apos;s time.</p></div><div><ArrowRight className="size-5" /><h3 className="mt-5 text-lg font-semibold">Move forward</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Turn responses into momentum with a workspace built for action.</p></div></div></div></section>
    </main>
  );
}
